* Commentary

Bitcoin donations gratefully accepted: 1FgnGFwRES9MGzoieRDWLmLkjqMT3AsjQF

This library provides functions for extracting/scraping text from buffers.
The `extract-matching-strings' and `extract-matching-rectangles' macros allow you to perform
simple extractions, but for more complex tasks there is `extract-text'.
This macro allows complex text extraction specifications using a kind of dsl for text extraction.
You can use included wrapper functions for picking out individual bits of text, or define your own
and save them in `extract-text-wrappers'. You can specify how many times to repeat each individual extraction,
how to handle errors or missing values, restrict the buffer for finding certain extractions, how to structure
&/or transform the output, etc. See the docstring for `extract-text' for more details.
* Functions
 - `match-strings' : Return a list of all strings matched by last search.
 - `match-strings-no-properties' : Return a list of all strings matched by last search.
 - `extract-matching-strings' : Extract strings from current buffer that match subexpressions of REGEXP.
 - `extract-matching-rectangle' : Extract a rectangle of text (list of strings) from the current buffer.
 - `copy-rectangle-to-buffer' : Copy a rectangular region of the current buffer to a new buffer.
* Macros
 - `extract-text' : Extract text from buffer according to specifications in ARGS.
 - `extract-text-from-buffers' : Extract text from buffers listed in BUFFERS or matching regexp BUFFERS.
 - `extract-text-from-files' : Extract text from FILES.
* Options
 - `extract-text-wrappers' : A list of wrapper functions that can be used with `extract-text'.
* Requirements
Features that might be required by this library:

cl, dash, macro-utils, keyword-arg-macros

* Installation

Put extract-text.el in a directory in your load-path, e.g. ~/.emacs.d/
You can add a directory to your load-path with the following line in ~/.emacs
(add-to-list 'load-path (expand-file-name "~/elisp"))
where ~/elisp is the directory you want to add 
(you don't need to do this for ~/.emacs.d - it's added by default).

Add the following to your ~/.emacs startup file.

(require 'extract-text)


